precio: 10
##Costo de crear una nueva organización
comando-help:
    - " "
    - "§6SERVIMERCADO COMANDOS"
    - " "
    - "§f/mercado nuevo <nombre>"
    - "§bCrea una organización."
    - " "
    - "§f/mercado invitar <organización> <usuario>"
    - "§bInvita a un usuario a tu organización"
    - " "
    - "§f/mercado aceptar <organización>"
    - "§bAcepta la invitación a una organización"
    - " "
    - "§f/mercado rechazar <organización>"
    - "§bRechaza la invitación a una organización"
    - " "
    - "§f/mercado proyecto <organización> <nombre> <precio> <plazo>"
    - "§bCrea un proyecto para contratar trabajadores."
    - "§aNota: Debes incluir el precio que pagarás y el plazo del proyecto en horas."
    - " "
    - "§f/mercado proyectos"
    - "§bVer los proyectos de las organizaciones."
    - " "
    - "§f/mercado postular <organización> <proyecto> <tiempo>"
    - "§bPostular a un proyecto."
    - "§aNota: Debes especificar el tiempo que te tomará en horas."
    - " "
    - "§f/mercado cancelar <organización> <proyecto>"
    - "§bCancelar la postulación o salirte de un proyecto."
    - "§aNota: Tendras una penalización de dinero si te sales muy tarde."
    - " "
    - "§f/mercado info <organización>"
    - "§bVer la información acerca de una organización."
    - " "