name: ServiMercado
author: ServiCraft
version: 1.0
main: org.servicraft.servimercado.EventClass
commands:
    mercado:
        description: Comando principal
        usage: /mercado
    sociedad:
        description: Uso exclusivo para sociedades
        usage: /sociedad
    gremio:
        description: Uso exclusivo para gremios
        usage: /gremio